--------------------------------------------------------
--  파일이 생성됨 - 목요일-11월-01-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FREEBOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SOLSTUDY"."FREEBOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BURGER DRINK
--------------------------------------------------------

  CREATE TABLE "SOLSTUDY"."BURGER DRINK" 
   (	"DRINKID" NUMBER(2,0), 
	"DRINKNAME" VARCHAR2(40 BYTE), 
	"PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BURGER_BURGER
--------------------------------------------------------

  CREATE TABLE "SOLSTUDY"."BURGER_BURGER" 
   (	"BURGERID" NUMBER(2,0), 
	"BURGERNAME" VARCHAR2(40 BYTE), 
	"PRICE" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BURGER_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SOLSTUDY"."BURGER_CUSTOMER" 
   (	"CUSTID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"CUSTNAME" VARCHAR2(40 BYTE), 
	"COLUMN1" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FREEBOOK
--------------------------------------------------------

  CREATE TABLE "SOLSTUDY"."FREEBOOK" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"SUBJECT" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"PWD" VARCHAR2(50 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SOLSTUDY."BURGER DRINK"
SET DEFINE OFF;
REM INSERTING into SOLSTUDY.BURGER_BURGER
SET DEFINE OFF;
REM INSERTING into SOLSTUDY.BURGER_CUSTOMER
SET DEFINE OFF;
REM INSERTING into SOLSTUDY.FREEBOOK
SET DEFINE OFF;
Insert into SOLSTUDY.FREEBOOK (IDX,NAME,SUBJECT,CONTENT,PWD,REGDATE) values (1,'장만옥','하이','반갑다','0000',to_date('2018/10/29','YYYY/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007049
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOLSTUDY"."SYS_C007049" ON "SOLSTUDY"."FREEBOOK" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BURGER_BURGER
--------------------------------------------------------

  ALTER TABLE "SOLSTUDY"."BURGER_BURGER" MODIFY ("BURGERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREEBOOK
--------------------------------------------------------

  ALTER TABLE "SOLSTUDY"."FREEBOOK" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
